http:
  port: "8081"

db:
  sapi:
    username : "![aUcRcyZBnu0Ex6kMCU6s8UJ4GZ1x1tFIWGAhxumOYcI=]"
    password : "![A7AC5rV0ATN3EqHpeb6u0Q==]"
    securityToken : "![8jXNCc4uJSqv4xpcoOx2xCGlylnUtf+0kH35k6869q4=]"
    url: "![/b34YjT0iq/BVM16mvPw+n1HiY1j97ks/rHDqS/NaCTWgUSWrd29/iU6Hi3uVR1QlSemt36CSdPoS0uhG5hAAQ==]"

mule:
  env: "local"      

json:
  logger:
    application:
      name: "as-micorp-sapi"
      version: "1.0.0"
       